export interface TarotCard {
  id: string
  name: string
  arcana: 'major' | 'minor'
  suit?: 'wands' | 'cups' | 'swords' | 'pentacles'
  number: number
  symbol: string
  keywords: string[]
  upright: string
  reversed: string
  description: string
  symbolism: string
}

// ── Element system ────────────────────────────────────────────────────────────

interface ElementInfo {
  name: string
  glyph: string
  quality: string
  ruler?: string
}

const SUIT_ELEMENTS: Record<string, ElementInfo> = {
  wands:     { name: 'Fire',  glyph: '🔥', quality: 'Passion, will, inspiration, transformative energy' },
  cups:      { name: 'Water', glyph: '💧', quality: 'Emotion, intuition, love, the unconscious depths' },
  swords:    { name: 'Air',   glyph: '💨', quality: 'Thought, communication, truth, the cutting of illusion' },
  pentacles: { name: 'Earth', glyph: '🌿', quality: 'Matter, body, work, abundance, the tangible world' },
}

const MAJOR_ELEMENTS: Record<number, ElementInfo> = {
  0:  { name: 'Air',   glyph: '💨', quality: 'Freedom, pure potential, the unbound spirit', ruler: 'Uranus' },
  1:  { name: 'Air',   glyph: '💨', quality: 'Swift intellect, communication, the mercurial will', ruler: 'Mercury' },
  2:  { name: 'Water', glyph: '💧', quality: 'Intuition, mystery, the tidal pull of the unconscious', ruler: 'Moon' },
  3:  { name: 'Earth', glyph: '🌿', quality: 'Fertility, creative abundance, the body of the goddess', ruler: 'Venus' },
  4:  { name: 'Fire',  glyph: '🔥', quality: 'Authority, drive, the will to build and command', ruler: 'Aries' },
  5:  { name: 'Earth', glyph: '🌿', quality: 'Tradition, structure, the sacred body of institution', ruler: 'Taurus' },
  6:  { name: 'Air',   glyph: '💨', quality: 'Connection, duality, the breath exchanged between two', ruler: 'Gemini' },
  7:  { name: 'Water', glyph: '💧', quality: 'Feeling, home, the protective shell of inner life', ruler: 'Cancer' },
  8:  { name: 'Fire',  glyph: '🔥', quality: 'Courage, heart-strength, the radiance of inner vitality', ruler: 'Leo' },
  9:  { name: 'Earth', glyph: '🌿', quality: 'Discernment, service, the sacred harvest of wisdom', ruler: 'Virgo' },
  10: { name: 'Fire',  glyph: '🔥', quality: 'Expansion, fortune, the turning of great cycles', ruler: 'Jupiter' },
  11: { name: 'Air',   glyph: '💨', quality: 'Clarity, fairness, the weighing of truth on still scales', ruler: 'Libra' },
  12: { name: 'Water', glyph: '💧', quality: 'Surrender, the wisdom of letting go, the deep still', ruler: 'Neptune' },
  13: { name: 'Water', glyph: '💧', quality: 'Transformation, the deep change of tides and seasons', ruler: 'Scorpio' },
  14: { name: 'Fire',  glyph: '🔥', quality: 'Purpose, vision, the arrow aimed at a distant truth', ruler: 'Sagittarius' },
  15: { name: 'Earth', glyph: '🌿', quality: 'Matter, discipline, the shadow cast by the physical world', ruler: 'Capricorn' },
  16: { name: 'Fire',  glyph: '🔥', quality: 'Sudden force, revolution, the purifying bolt of truth', ruler: 'Mars' },
  17: { name: 'Air',   glyph: '💨', quality: 'Vision, freedom, the wide breath of hope and renewal', ruler: 'Aquarius' },
  18: { name: 'Water', glyph: '💧', quality: 'Illusion, depth, the tidal unknown beneath the surface', ruler: 'Pisces' },
  19: { name: 'Fire',  glyph: '🔥', quality: 'Radiance, joy, the light that sustains and reveals all', ruler: 'Sun' },
  20: { name: 'Fire',  glyph: '🔥', quality: 'Awakening, renewal, the final transformative flame', ruler: 'Pluto' },
  21: { name: 'Earth', glyph: '🌿', quality: 'Completion, integration, the whole made fully manifest', ruler: 'Saturn' },
}

export function getElement(card: TarotCard): ElementInfo {
  if (card.arcana === 'minor' && card.suit) return SUIT_ELEMENTS[card.suit]
  return MAJOR_ELEMENTS[card.number]
}

// ── Numerology system ─────────────────────────────────────────────────────────

interface NumerologyInfo {
  title: string
  meaning: string
}

const NUMEROLOGY_MAP: Record<number, NumerologyInfo> = {
  0:  { title: 'Zero — The Void',      meaning: 'Pure potential before creation, the pregnant pause of infinite possibility.' },
  1:  { title: 'One — The Beginning',  meaning: 'Unity, initiation, the singular spark that sets all things in motion.' },
  2:  { title: 'Two — Duality',        meaning: 'Partnership, balance, the dance between two opposing or complementary forces.' },
  3:  { title: 'Three — Growth',       meaning: 'The fruit of union — creativity, expression, the energy of collaboration.' },
  4:  { title: 'Four — Structure',     meaning: 'Stability, foundation, the four corners that hold a thing firmly in place.' },
  5:  { title: 'Five — Change',        meaning: 'The dynamic disruptor — conflict, freedom, and what breaks old forms open.' },
  6:  { title: 'Six — Harmony',        meaning: 'Love, healing, responsibility — the number that seeks beauty and balance.' },
  7:  { title: 'Seven — Mystery',      meaning: 'The seeker\'s number — inner wisdom, solitude, the deep inquiry into truth.' },
  8:  { title: 'Eight — Power',        meaning: 'Mastery, cause and effect, the lemniscate of infinite cycles in motion.' },
  9:  { title: 'Nine — Completion',    meaning: 'Fulfillment, the wisdom earned at the end of a long journey.' },
  10: { title: 'Ten — Wholeness',      meaning: 'The completion of a cycle and the seed of a new one — unity returning.' },
  11: { title: 'Page — Awakening',     meaning: 'Receptive, curious, at the threshold — the student who has just arrived.' },
  12: { title: 'Knight — Quest',       meaning: 'Purposeful motion — the archetype of the seeker crossing unknown terrain.' },
  13: { title: 'Queen — Mastery',      meaning: 'Wisdom internalized, authority worn naturally — she leads by knowing deeply.' },
  14: { title: 'King — Command',       meaning: 'The fullest expression of the suit\'s power — mature, certain, sovereign.' },
}

export function getNumerology(number: number): NumerologyInfo {
  return NUMEROLOGY_MAP[number] ?? { title: String(number), meaning: '' }
}

// ── Card data ──────────────────────────────────────────────────────────────────

const tarotCards: TarotCard[] = [
  // ── Major Arcana ──────────────────────────────────────────────────────────
  {
    id: 'the-fool',
    name: 'The Fool',
    arcana: 'major',
    number: 0,
    symbol: '🌬️',
    keywords: ['beginnings', 'innocence', 'spontaneity', 'free spirit'],
    upright: 'New beginnings, faith in the future, inexperienced, not knowing what to expect, having beginner\'s luck, improvisation and believing in the universe.',
    reversed: 'Holding back, recklessness, risk-taking, naivety, foolishness, carelessness, distraction.',
    description: 'The Fool stands at the edge of a cliff, ready to step into the unknown with nothing but a small sack and a white rose. He gazes upward, carefree and full of wonder.',
    symbolism: 'The white rose signals purity of intent; the small pack, the lightness of unladen beginning. The cliff beneath his foot is not danger — it is the invitation of infinite possibility.',
  },
  {
    id: 'the-magician',
    name: 'The Magician',
    arcana: 'major',
    number: 1,
    symbol: '✨',
    keywords: ['willpower', 'desire', 'creation', 'manifestation'],
    upright: 'Willpower, desire, being resourceful, skill, ability to concentrate, turning ideas into action.',
    reversed: 'Trickery, illusions, deception, manipulation, lack of focus, untapped talents.',
    description: 'The Magician stands before a table bearing the four suit symbols. One hand points to the sky, the other to the earth — as above, so below.',
    symbolism: 'The four elemental tools on the table signal mastery of all realms. The lemniscate above his head is the seal of infinite will. One hand raised, one lowered — the bridge between heaven and earth is the magician himself.',
  },
  {
    id: 'the-high-priestess',
    name: 'The High Priestess',
    arcana: 'major',
    number: 2,
    symbol: '🌙',
    keywords: ['intuition', 'mystery', 'subconscious', 'inner voice'],
    upright: 'Intuition, sacred knowledge, divine feminine, the subconscious mind, passive reception of knowledge.',
    reversed: 'Secrets, disconnected from intuition, withdrawal, silence, lack of center.',
    description: 'She sits between two pillars at the entrance to the veil. A crescent moon rests at her feet and she holds a sacred scroll.',
    symbolism: 'Twin pillars B and J (Boaz and Jachin) mark the threshold of the hidden temple. The veil of pomegranates conceals the mystery; the crescent at her feet speaks of cyclical, lunar wisdom. The scroll rests half-hidden — all knowing is partial.',
  },
  {
    id: 'the-empress',
    name: 'The Empress',
    arcana: 'major',
    number: 3,
    symbol: '🌿',
    keywords: ['femininity', 'beauty', 'nature', 'nurturing', 'abundance'],
    upright: 'Femininity, beauty, nature, abundance, fertility, motherhood, creativity.',
    reversed: 'Creative block, dependence on others, smothering, lack of growth, disharmony.',
    description: 'The Empress sits on a throne amid lush nature, wearing a crown of twelve stars. She embodies the fertile earth and creative abundance.',
    symbolism: 'A crown of twelve stars mirrors the full zodiac — she holds all cycles. Ripe wheat at her feet speaks of earth\'s abundance; the waterfall flows behind her, endlessly generous. The heart-shaped shield bears Venus\'s glyph.',
  },
  {
    id: 'the-emperor',
    name: 'The Emperor',
    arcana: 'major',
    number: 4,
    symbol: '⚡',
    keywords: ['authority', 'structure', 'control', 'fatherhood'],
    upright: 'Authority, establishment, structure, a father figure, solid foundation, rationality.',
    reversed: 'Domination, excessive control, lack of discipline, inflexibility, being autocratic.',
    description: 'The Emperor sits on a stone throne adorned with ram heads, representing Aries energy — power, authority, and the will to lead.',
    symbolism: 'Ram-head armrests mark Aries authority — action and conquest. The stone throne is unmovable will; the red robe, worldly power. The barren orange mountains behind speak of a landscape shaped entirely by one who commands.',
  },
  {
    id: 'the-hierophant',
    name: 'The Hierophant',
    arcana: 'major',
    number: 5,
    symbol: '⛪',
    keywords: ['tradition', 'conformity', 'morality', 'ethics'],
    upright: 'Spiritual wisdom, religious beliefs, conformity, tradition, institutions, a mentor.',
    reversed: 'Personal beliefs, freedom, challenging the status quo, rejection of tradition.',
    description: 'The Hierophant sits between two pillars of a sacred temple, his hand raised in blessing while two devotees kneel before him.',
    symbolism: 'The triple-barred papal cross signals spiritual authority layered three-deep. Crossed keys at his feet unlock both earthly and divine wisdom. Two kneeling acolytes show that tradition is transmitted through living practice, not words alone.',
  },
  {
    id: 'the-lovers',
    name: 'The Lovers',
    arcana: 'major',
    number: 6,
    symbol: '💫',
    keywords: ['love', 'harmony', 'relationships', 'values alignment'],
    upright: 'Love, harmony, relationships, values alignment, choices, partnerships.',
    reversed: 'Self-love, disharmony, imbalance, misalignment of values, difficulty with choices.',
    description: 'Two figures stand beneath an angel, bathed in golden light. A great choice lies before them — one that will define their path.',
    symbolism: 'The angel Raphael (healing, air) blesses from above. The tree of knowledge with its serpent stands behind the woman; the tree of flame behind the man. Two natures, one choice — the soul is defined by what it selects.',
  },
  {
    id: 'the-chariot',
    name: 'The Chariot',
    arcana: 'major',
    number: 7,
    symbol: '🌟',
    keywords: ['control', 'willpower', 'success', 'determination'],
    upright: 'Control, willpower, success, action, determination, triumph over obstacles.',
    reversed: 'Self-discipline lacking, opposition, lack of direction, no control.',
    description: 'A victorious warrior rides a chariot pulled by two sphinxes — one black, one white. He steers through willpower alone, holding no reins.',
    symbolism: 'Two sphinxes pull in opposite directions yet the chariot moves forward — will alone reconciles opposing forces. The starry canopy above links the warrior to the cosmos. He holds no reins; mind is the only instrument of direction.',
  },
  {
    id: 'strength',
    name: 'Strength',
    arcana: 'major',
    number: 8,
    symbol: '🦁',
    keywords: ['strength', 'courage', 'patience', 'inner power'],
    upright: 'Strength, courage, patience, control, compassion, inner power, bravery.',
    reversed: 'Inner strength, self-doubt, low energy, raw emotion, cowardice.',
    description: 'A woman gently closes the mouth of a lion with her bare hands. Above her head floats the lemniscate — the symbol of infinite power.',
    symbolism: 'The lemniscate above the woman\'s head signals infinite, effortless power. Her white robe is pure intention. The lion is raw instinct — not defeated, but honored and gently redirected by compassion rather than force.',
  },
  {
    id: 'the-hermit',
    name: 'The Hermit',
    arcana: 'major',
    number: 9,
    symbol: '🕯️',
    keywords: ['soul-searching', 'introspection', 'being alone', 'guidance'],
    upright: 'Soul-searching, introspection, inner guidance, solitude, a phase of withdrawal.',
    reversed: 'Isolation, loneliness, withdrawal, lost your way, anti-social.',
    description: 'An aged figure stands alone atop a snowy mountain, holding a glowing lantern. He has withdrawn from the world to seek inner truth.',
    symbolism: 'The lantern holds a six-pointed star — the Seal of Solomon, wisdom found through experience. He has climbed to the highest peak not to escape the world but to hold the light steady for those who follow the path below.',
  },
  {
    id: 'wheel-of-fortune',
    name: 'Wheel of Fortune',
    arcana: 'major',
    number: 10,
    symbol: '☯️',
    keywords: ['good luck', 'karma', 'life cycles', 'destiny', 'turning point'],
    upright: 'Good luck, karma, life cycles, destiny, a turning point, fortune.',
    reversed: 'Bad luck, lack of control, clinging to control, unwelcome changes.',
    description: 'A great wheel turns in the cosmos, surrounded by mystical creatures. TARO is inscribed on its rim — the wheel of fate spins endlessly.',
    symbolism: 'TARO inscribed on the wheel can be read in any direction — fate is circular, not linear. In the corners: bull, eagle, angel, lion — the four fixed zodiac signs reading their books amid the spin. Anubis rises; Typhon descends; the sphinx above knows the secret.',
  },
  {
    id: 'justice',
    name: 'Justice',
    arcana: 'major',
    number: 11,
    symbol: '⚖️',
    keywords: ['justice', 'fairness', 'truth', 'cause and effect'],
    upright: 'Justice, fairness, truth, cause and effect, law, balance, integrity.',
    reversed: 'Unfairness, lack of accountability, dishonesty, legal complications.',
    description: 'A robed figure sits on a throne between two stone pillars, holding scales in one hand and a sword in the other — the embodiment of impartial truth.',
    symbolism: 'The double-edged sword cuts both ways and has no favorites. The scales rest in perfect equilibrium — not weighted by sentiment. The purple veil behind conceals the full mystery of what law can and cannot see.',
  },
  {
    id: 'the-hanged-man',
    name: 'The Hanged Man',
    arcana: 'major',
    number: 12,
    symbol: '🌀',
    keywords: ['suspension', 'restriction', 'letting go', 'sacrifice'],
    upright: 'Pause, surrender, letting go, new perspectives, sacrifice for wisdom.',
    reversed: 'Delays, resistance, stalling, indecision, avoiding sacrifice.',
    description: 'A figure hangs upside-down from a living tree, one leg crossed, arms behind back. His expression is serene — he has chosen to surrender.',
    symbolism: 'The living wood of the T-cross tree — sacrifice chosen, not imposed. Legs crossed in a deliberate figure-four. The radiant halo is enlightenment earned through inversion. His expression is calm: a new world is visible from here.',
  },
  {
    id: 'death',
    name: 'Death',
    arcana: 'major',
    number: 13,
    symbol: '🌹',
    keywords: ['endings', 'change', 'transformation', 'transition'],
    upright: 'Endings, change, transformation, transition, letting go of the past.',
    reversed: 'Resistance to change, personal transformation, inner purging, stagnation.',
    description: 'A skeletal knight on a white horse carries a black banner. Before him, all people from all walks of life must bow — none are exempt from change.',
    symbolism: 'The white rose banner heralds purity through ending. The white horse is the color of spirit stripped to essence. Pope, king, child, and maiden all stand before him equally — rank offers no exemption. Behind, the sun rises between two towers.',
  },
  {
    id: 'temperance',
    name: 'Temperance',
    arcana: 'major',
    number: 14,
    symbol: '🌊',
    keywords: ['balance', 'moderation', 'patience', 'purpose'],
    upright: 'Balance, moderation, patience, purpose, meaning, higher learning.',
    reversed: 'Imbalance, excess, lack of long-term vision, self-healing needed.',
    description: 'An angel pours water between two cups, one foot on land and one in the water. A path of golden light leads to a radiant crown in the distance.',
    symbolism: 'A triangle inscribed within a square on the robe: divinity within matter. Water flows freely between cups without spilling — perfect, practiced balance. One foot on land and one in water: the bridge between the material and the spiritual held steady.',
  },
  {
    id: 'the-devil',
    name: 'The Devil',
    arcana: 'major',
    number: 15,
    symbol: '🔗',
    keywords: ['shadow self', 'attachment', 'addiction', 'restriction'],
    upright: 'Shadow self, attachment, addiction, restriction, sexuality, bondage.',
    reversed: 'Releasing limiting beliefs, exploring dark thoughts, detachment, freedom.',
    description: 'A horned figure sits on a throne while two chained humans stand below. The chains are loose — they could leave, but choose to stay.',
    symbolism: 'Baphomet\'s goat-head throne is the face of shadow and material obsession. The inverted pentagram: matter placed above spirit. The chains around the figures\' necks are visibly loose — the bondage exists because it has not been examined.',
  },
  {
    id: 'the-tower',
    name: 'The Tower',
    arcana: 'major',
    number: 16,
    symbol: '🔥',
    keywords: ['sudden change', 'upheaval', 'chaos', 'revelation'],
    upright: 'Sudden change, upheaval, chaos, revelation, awakening, disaster.',
    reversed: 'Personal transformation, fear of change, averting disaster, resistance.',
    description: 'Lightning strikes a tall tower, sending flames out of its windows and two figures tumbling to the ground. Sometimes truth arrives like thunder.',
    symbolism: 'The lightning bolt tears the crown from the tower — the ego\'s false pinnacle is struck down by sudden revelation. Flames pour from every window; two figures fall into open air. The destruction is total. So is the liberation.',
  },
  {
    id: 'the-star',
    name: 'The Star',
    arcana: 'major',
    number: 17,
    symbol: '⭐',
    keywords: ['hope', 'faith', 'purpose', 'renewal', 'spirituality'],
    upright: 'Hope, faith, purpose, renewal, spirituality, inspiration, serenity.',
    reversed: 'Lack of faith, despair, self-trust issues, disconnection, hopelessness.',
    description: 'A woman kneels by a pool under a vast star-filled sky. She pours water onto the earth and into the pool — a gesture of infinite renewal.',
    symbolism: 'Eight stars — the largest a north star of pure hope. The naked woman\'s vulnerability is her power. Water poured simultaneously onto earth and into the pool renews both the physical and the spiritual. The bird in the tree is Ibis, the soul freed.',
  },
  {
    id: 'the-moon',
    name: 'The Moon',
    arcana: 'major',
    number: 18,
    symbol: '🌕',
    keywords: ['illusion', 'fear', 'the subconscious', 'confusion'],
    upright: 'Illusion, fear, the unknown, confusion, complexity, secrets, subconscious.',
    reversed: 'Release of fear, repressed emotion, inner confusion, healing of illusions.',
    description: 'Between two towers, a path winds past a wolf and a dog. The moon above wears a face and drips yods — the way forward is uncertain.',
    symbolism: 'Yods fall like divine dew from the moon\'s face. A crayfish emerges from the primordial pool — the unconscious surfacing. A wolf and a domestic dog both howl upward: the wild and the tamed face the same inscrutable mystery.',
  },
  {
    id: 'the-sun',
    name: 'The Sun',
    arcana: 'major',
    number: 19,
    symbol: '☀️',
    keywords: ['positivity', 'fun', 'warmth', 'success', 'vitality'],
    upright: 'Positivity, fun, warmth, success, vitality, joy, confidence, clarity.',
    reversed: 'Inner child, feeling down, overly optimistic, ego, sadness, pessimism.',
    description: 'A child rides a white horse beneath a blazing sun, arms wide open. Sunflowers grow behind a garden wall — pure joy radiates from every element.',
    symbolism: 'Straight and wavy rays alternate around the sun — consciousness and the unconscious radiating together. The naked child on horseback, arms flung wide: pure, unashamed, armor-free joy. Even the garden wall cannot contain what blooms inside.',
  },
  {
    id: 'judgement',
    name: 'Judgement',
    arcana: 'major',
    number: 20,
    symbol: '📯',
    keywords: ['judgement', 'rebirth', 'inner calling', 'absolution'],
    upright: 'Judgement, rebirth, inner calling, absolution, reflection, reckoning.',
    reversed: 'Self-doubt, inner critic, ignoring the call, self-loathing, refusal of growth.',
    description: 'From the clouds, an angel blows a trumpet. Figures rise from graves in response. This is not an ending — it is an awakening.',
    symbolism: 'The angel sounds the trumpet of awakening; a white cross flag signals the new purity of resurrection. The figures rise not in fear but in answer. Even the icy mountains behind cannot stand between the soul and its calling.',
  },
  {
    id: 'the-world',
    name: 'The World',
    arcana: 'major',
    number: 21,
    symbol: '🌍',
    keywords: ['completion', 'integration', 'accomplishment', 'travel'],
    upright: 'Completion, integration, accomplishment, travel, wholeness, harmony.',
    reversed: 'Seeking personal closure, short-cuts, delays, incompleteness.',
    description: 'A dancer is surrounded by an oval wreath, holding two wands. The four fixed signs of the zodiac appear in the corners — all is in harmony.',
    symbolism: 'The laurel wreath frames completion — this is victory acknowledged by the cosmos. The dancer holds two wands: power to begin and to end, held simultaneously. Four zodiac creatures crown the corners: the whole of creation witnesses the arrival.',
  },

  // ── Wands ─────────────────────────────────────────────────────────────────
  {
    id: 'ace-of-wands',
    name: 'Ace of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 1,
    symbol: '🔥',
    keywords: ['creation', 'willpower', 'inspiration', 'desire'],
    upright: 'Inspiration, new opportunities, growth, potential, a spark of creativity.',
    reversed: 'Lack of energy, delays, blocked creativity, false start.',
    description: 'A hand emerges from a cloud gripping a budding wand. Fresh leaves sprout from it — a pure creative impulse waiting to take root.',
    symbolism: 'The hand emerging from cloud is the divine gift of creative impulse — given, not earned. Fresh leaves spring from the wand before it is even planted. A castle gleams in the distance: what this spark might one day become.',
  },
  {
    id: 'two-of-wands',
    name: 'Two of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 2,
    symbol: '🔥',
    keywords: ['future planning', 'progress', 'decisions', 'discovery'],
    upright: 'Future planning, progress, decisions, discovery, distant possibilities.',
    reversed: 'Personal goals, inner alignment, fear of unknown, lack of planning.',
    description: 'A figure holds a globe while looking out from a parapet. Two wands flank him — one is fixed, the future is open and vast.',
    symbolism: 'The globe held in the hand is the world already grasped in imagination. One wand is already planted; one is still held — decision is half-made. The distant sea horizon is not threat but invitation. The world is smaller than it looks.',
  },
  {
    id: 'three-of-wands',
    name: 'Three of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 3,
    symbol: '🔥',
    keywords: ['progress', 'expansion', 'foresight', 'overseas'],
    upright: 'Progress, expansion, foresight, overseas opportunities, anticipation.',
    reversed: 'Playing small, lack of foresight, unexpected delays, return from travel.',
    description: 'A merchant stands watching ships sail across the sea. Plans are in motion — the first ships have departed and the horizon promises return.',
    symbolism: 'Three wands stand planted as ships sail toward the horizon — the journey has already launched. The figure watches from high ground: not anxiously, but with the calm of one who planned well. Patience here is active, not passive.',
  },
  {
    id: 'four-of-wands',
    name: 'Four of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 4,
    symbol: '🔥',
    keywords: ['celebration', 'joy', 'harmony', 'homecoming'],
    upright: 'Celebration, joy, harmony, relaxation, homecoming, community, milestones.',
    reversed: 'Personal celebration, inner harmony, conflict with others, transition.',
    description: 'Four wands support a garland beneath which two joyful figures dance. A celebration is underway — a milestone has been reached.',
    symbolism: 'Four wands form an arch of stability beneath a harvest garland. The castle behind promises that security endures beyond the feast. The dancing figures celebrate not just an event but the foundation that made it possible.',
  },
  {
    id: 'five-of-wands',
    name: 'Five of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 5,
    symbol: '🔥',
    keywords: ['disagreement', 'competition', 'strife', 'tension'],
    upright: 'Disagreement, competition, strife, tension, conflict, chaos, diversity.',
    reversed: 'Avoiding conflict, respecting differences, internal conflict, finding harmony.',
    description: 'Five young men brandish wands at each other in a seemingly chaotic melee. No one is struck — this is spirited competition, not war.',
    symbolism: 'Five young men clash wands in apparent chaos — yet no one is truly struck. The varied clothing signals five different backgrounds and views. This is the creative friction that, if engaged honestly, forges something new.',
  },
  {
    id: 'six-of-wands',
    name: 'Six of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 6,
    symbol: '🔥',
    keywords: ['success', 'public recognition', 'progress', 'self-confidence'],
    upright: 'Success, public recognition, progress, self-confidence, victory, triumph.',
    reversed: 'Private achievement, personal definition of success, fall from grace, egotism.',
    description: 'A rider on horseback wears a victory wreath while crowds cheer. The six wands are held high — a moment of public triumph.',
    symbolism: 'The victory wreath on both horse and rider doubles the laurel. Six wands rise in procession around the rider; the crowd\'s upraised hands signal collective recognition. The triumph is real — and it is shared.',
  },
  {
    id: 'seven-of-wands',
    name: 'Seven of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 7,
    symbol: '🔥',
    keywords: ['challenge', 'competition', 'perseverance', 'defensiveness'],
    upright: 'Challenge, competition, protection, perseverance, maintaining position.',
    reversed: 'Giving up, overwhelmed, exhausted, backing down.',
    description: 'A figure stands on high ground fending off six wands below. The high ground is hard won and must be defended.',
    symbolism: 'The lone figure stands on a raised ledge, six wands pressing from below. The high ground is both advantage and isolation. The figure\'s mismatched shoes suggest urgency — there was barely time to dress before the defense began.',
  },
  {
    id: 'eight-of-wands',
    name: 'Eight of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 8,
    symbol: '🔥',
    keywords: ['movement', 'fast paced change', 'action', 'alignment'],
    upright: 'Movement, fast paced change, action, alignment, air travel, rapid progress.',
    reversed: 'Delays, frustration, resisting change, internal alignment needed.',
    description: 'Eight wands fly through the air in perfect alignment — rapid movement, swift communication, things are moving fast now.',
    symbolism: 'Eight wands arc through clear sky in perfect parallel — no obstacles, no divergence. They move as one unit without a hand to guide them. Pure, aligned momentum needs nothing but itself to reach its destination.',
  },
  {
    id: 'nine-of-wands',
    name: 'Nine of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 9,
    symbol: '🔥',
    keywords: ['resilience', 'grit', 'last stand', 'persistence'],
    upright: 'Resilience, grit, last stand, persistence, stamina, courage.',
    reversed: 'Inner resources, struggling, overwhelm, defensive, paranoia.',
    description: 'A wounded but unbowed figure leans on a wand while eight more stand behind. One more push is all that remains.',
    symbolism: 'A bandaged warrior leans on his wand, eight more standing ranked behind him. His expression is wary but unbroken — he has absorbed every hit and is still here. The final effort is not ahead of him; it has already begun.',
  },
  {
    id: 'ten-of-wands',
    name: 'Ten of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 10,
    symbol: '🔥',
    keywords: ['burden', 'extra responsibility', 'hard work', 'completion'],
    upright: 'Burden, extra responsibility, hard work, completion, carrying the load.',
    reversed: 'Doing it all yourself, collapse, inability to delegate, burnout.',
    description: 'A figure struggles to carry ten heavy wands toward a town just visible in the distance. The end is near — but the weight is immense.',
    symbolism: 'Ten wands obscure the figure\'s face entirely — the burden has become the whole world. The destination town is almost within reach. The card asks: what are you carrying that no longer needs to be carried by you alone?',
  },
  {
    id: 'page-of-wands',
    name: 'Page of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 11,
    symbol: '🔥',
    keywords: ['exploration', 'excitement', 'freedom', 'adventure'],
    upright: 'Exploration, excitement, freedom, adventurousness, courage, new ideas.',
    reversed: 'Lack of direction, procrastination, creating conflict, pessimism.',
    description: 'A young adventurer holds a tall wand and gazes at it with wonder. Salamanders on his tunic represent transformation through fire.',
    symbolism: 'Salamanders on the page\'s tunic — creatures said to live within fire — signal transformation through wholehearted engagement. He gazes at the wand not with use in mind but with pure, open wonder. The desert behind is wide open.',
  },
  {
    id: 'knight-of-wands',
    name: 'Knight of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 12,
    symbol: '🔥',
    keywords: ['energy', 'passion', 'lust', 'adventure', 'impulsiveness'],
    upright: 'Energy, passion, inspired action, adventure, impulsiveness, hot-headedness.',
    reversed: 'Passion project, haste, scattered energy, delays, frustration.',
    description: 'A knight charges forward on a rearing horse, wand aloft, plumes flying. He acts first and thinks second — but his energy is unstoppable.',
    symbolism: 'The knight\'s armor is decorated with salamanders — fire that regenerates. His horse rears, plumes fly in all directions. The desert behind is already conquered. He does not slow; he trusts that direction will reveal itself in motion.',
  },
  {
    id: 'queen-of-wands',
    name: 'Queen of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 13,
    symbol: '🔥',
    keywords: ['courage', 'confidence', 'independence', 'warmth'],
    upright: 'Courage, confidence, independence, social butterfly, determination.',
    reversed: 'Self-respect, self-confidence, introverted, re-establish sense of self.',
    description: 'A crowned queen sits boldly on her throne, sunflowers in hand. A black cat rests at her feet — she is magnetic, warm, and fiercely capable.',
    symbolism: 'The sunflowers in her hand reach toward fire and light — as does she. The black cat at her feet signals hidden knowing and the unseen power of feminine mystery. The lions on her throne reflect the strength she carries without effort.',
  },
  {
    id: 'king-of-wands',
    name: 'King of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 14,
    symbol: '🔥',
    keywords: ['natural-born leader', 'vision', 'entrepreneur', 'honour'],
    upright: 'Natural-born leader, vision, entrepreneur, honour, big picture thinking.',
    reversed: 'Impulsiveness, haste, ruthless, high expectations.',
    description: 'A lion-throne king grips his wand and gazes forward with absolute conviction. His cloak bears salamanders — he transforms everything he touches.',
    symbolism: 'A robe of living salamanders: fire that transforms without consuming. The lion throne — king of instinct made sovereign. He holds his wand loosely; real power requires no visible effort. The small salamander at his feet bites its own tail — eternity.',
  },

  // ── Cups ──────────────────────────────────────────────────────────────────
  {
    id: 'ace-of-cups',
    name: 'Ace of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 1,
    symbol: '💧',
    keywords: ['new feelings', 'spirituality', 'intuition', 'love'],
    upright: 'New feelings, spirituality, intuition, intimacy, love, compassion.',
    reversed: 'Emotional loss, blocked creativity, emptiness, repressed emotions.',
    description: 'A divine hand offers an overflowing cup, with a dove descending and streams of water pouring forth. Love and spirit flow in abundance.',
    symbolism: 'The cup overflows with five streams — spirit in superabundance, beyond what can be contained. A dove descends with a communion wafer; the lotus floats on the surface. This love does not begin within us — it arrives from beyond.',
  },
  {
    id: 'two-of-cups',
    name: 'Two of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 2,
    symbol: '💧',
    keywords: ['unified love', 'partnership', 'mutual attraction'],
    upright: 'Unified love, partnership, mutual attraction, relationships, connection.',
    reversed: 'Self-love, break-ups, disharmony, distrust, imbalance in relationship.',
    description: 'Two figures exchange cups in a pledge of mutual love. Above them floats the caduceus — a symbol of balanced exchange and healing.',
    symbolism: 'Two figures exchange cups in equal measure — this is love as a mutual gift, not a claim. The caduceus above bears a winged lion: the heart, when truly met, becomes courageous. Healing lives in the space between two open hands.',
  },
  {
    id: 'three-of-cups',
    name: 'Three of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 3,
    symbol: '💧',
    keywords: ['celebration', 'friendship', 'creativity', 'collaborations'],
    upright: 'Celebration, friendship, creativity, collaborations, community, reunion.',
    reversed: 'Independence, alone time, hardcore partying, three\'s a crowd.',
    description: 'Three women dance joyfully while raising their cups to the sky, surrounded by abundant fruit. This is pure communal celebration.',
    symbolism: 'Three women raise their cups in a toast surrounded by harvest abundance. The fruit, the open sky, the dance — nothing is withheld. Joy here is communal and rooted: grown from shared effort, offered without reserve.',
  },
  {
    id: 'four-of-cups',
    name: 'Four of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 4,
    symbol: '💧',
    keywords: ['meditation', 'contemplation', 'apathy', 'reevaluation'],
    upright: 'Meditation, contemplation, apathy, reevaluation, boredom, disconnection.',
    reversed: 'Sudden awareness, choosing happiness, acceptance, moving on.',
    description: 'A young man sits cross-legged under a tree, arms folded. Three cups stand before him, a fourth offered from a cloud — but he doesn\'t notice.',
    symbolism: 'The youth sits in closed posture — arms folded, inward-turned. Three cups stand before him unexamined. A fourth is extended from a cloud he cannot see from behind lowered eyes. Apathy makes us blind to what grace quietly offers.',
  },
  {
    id: 'five-of-cups',
    name: 'Five of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 5,
    symbol: '💧',
    keywords: ['regret', 'failure', 'disappointment', 'pessimism'],
    upright: 'Regret, failure, disappointment, pessimism, grief, loss, sorrow.',
    reversed: 'Personal setbacks, self-forgiveness, moving on, accepting loss.',
    description: 'A cloaked figure mourns over three spilled cups. But two cups still stand behind them, unseen. Loss is real — but not total.',
    symbolism: 'Three cups spill; two stand full and unseen behind the grieving figure. The black cloak is the full immersion in loss. The bridge in the distance still crosses the river — the way forward remains, waiting for the eyes to turn.',
  },
  {
    id: 'six-of-cups',
    name: 'Six of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 6,
    symbol: '💧',
    keywords: ['revisiting the past', 'childhood memories', 'innocence'],
    upright: 'Revisiting the past, childhood memories, innocence, joy, nostalgia.',
    reversed: 'Living in the past, forgiveness, lacking playfulness, naivety.',
    description: 'A child offers a cup full of white flowers to a smaller companion. The scene is tender and golden — a moment of pure, innocent giving.',
    symbolism: 'Six cups hold carefully tended white flowers — not coins, not water, but something given without measure. The older child offers without condition; the younger receives without suspicion. The golden light is memory\'s own warmth.',
  },
  {
    id: 'seven-of-cups',
    name: 'Seven of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 7,
    symbol: '💧',
    keywords: ['fantasy', 'illusion', 'wishful thinking', 'choices'],
    upright: 'Fantasy, illusion, wishful thinking, choices, imagination, daydreaming.',
    reversed: 'Alignment, clarity, becoming sober, making choices, reality check.',
    description: 'A silhouette gazes at seven cups floating in clouds, each containing a different vision. Which is real? Which is worth pursuing?',
    symbolism: 'Seven cups suspended in cloud each hold a different vision: castle, jewels, laurel, dragon, serpent, shrouded figure, radiant light. The gazing silhouette casts no shadow — in fantasy, we ourselves become unclear. All are real. None are chosen.',
  },
  {
    id: 'eight-of-cups',
    name: 'Eight of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 8,
    symbol: '💧',
    keywords: ['disappointment', 'abandonment', 'withdrawal', 'escapism'],
    upright: 'Disappointment, abandonment, withdrawal, escapism, walking away.',
    reversed: 'Trying again, returning home, acceptance, fear of moving on.',
    description: 'A figure walks away from eight standing cups toward the mountains under a waning moon. Something is being deliberately left behind.',
    symbolism: 'Eight cups are carefully stacked — they are not abandoned in disarray but left in order. The eclipse moon marks a completed cycle. The cloaked figure walks deliberately toward the mountains. The departure is chosen, not forced.',
  },
  {
    id: 'nine-of-cups',
    name: 'Nine of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 9,
    symbol: '💧',
    keywords: ['satisfaction', 'emotional stability', 'luxury', 'wish fulfilled'],
    upright: 'Satisfaction, emotional stability, luxury, wish fulfillment, contentment.',
    reversed: 'Lack of inner joy, overindulgence, materialism, dissatisfaction.',
    description: 'A rotund, contented figure sits with arms folded before nine gleaming cups arranged on a shelf. This is the "wish card" — desires fulfilled.',
    symbolism: 'Nine gleaming cups arranged on a cloth-draped shelf behind a satisfied, arms-folded figure. The cups face outward; he stares forward. Fulfillment has arrived — and yet something in the posture wonders what comes next.',
  },
  {
    id: 'ten-of-cups',
    name: 'Ten of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 10,
    symbol: '💧',
    keywords: ['divine love', 'blissful relationships', 'harmony', 'alignment'],
    upright: 'Divine love, blissful relationships, harmony, alignment, happy family.',
    reversed: 'Disconnection, misaligned values, struggling relationships, broken home.',
    description: 'A couple stands arm in arm as their children dance. Above them, ten cups form a rainbow arc. This is the card of utter, complete happiness.',
    symbolism: 'Ten cups form a rainbow arc — love made visible as a promise across the sky. A couple embraces; children dance freely. The house on the hill, the family, the open arms — all of it present at once. And all of it enough.',
  },
  {
    id: 'page-of-cups',
    name: 'Page of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 11,
    symbol: '💧',
    keywords: ['creative opportunities', 'intuitive messages', 'curiosity'],
    upright: 'Creative opportunities, intuitive messages, curiosity, imaginative.',
    reversed: 'New ideas, doubting intuition, creative blocks, emotional immaturity.',
    description: 'A young figure holds a cup from which a fish peers out. The page gazes at it with gentle wonder — a message arrives from the deep.',
    symbolism: 'A fish leans out of the page\'s cup to speak. The page does not recoil — he listens. The rolling ocean behind signals that intuitive messages rise from unpredictable depths. The message is always stranger than expected.',
  },
  {
    id: 'knight-of-cups',
    name: 'Knight of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 12,
    symbol: '💧',
    keywords: ['creativity', 'romance', 'charm', 'imagination', 'beauty'],
    upright: 'Creativity, romance, charm, imagination, beauty, idealism.',
    reversed: 'Overactive imagination, unrealistic, jealous, moody, disillusionment.',
    description: 'A gentle knight on a slow white horse bears a cup before him like an offering. He is the romantic messenger — grace personified.',
    symbolism: 'Fish decorate the knight\'s armor and his winged helmet — the marks of a soul who moves by feeling. His white horse advances slowly, deliberately. The cup is held before him as an offering or a question. He arrives as an invitation.',
  },
  {
    id: 'queen-of-cups',
    name: 'Queen of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 13,
    symbol: '💧',
    keywords: ['compassionate', 'caring', 'emotionally stable', 'intuitive'],
    upright: 'Compassionate, caring, emotionally stable, intuitive, in flow.',
    reversed: 'Inner feelings, self-care, self-love, codependency, inner child.',
    description: 'A queen gazes at a closed, ornate cup — unlike all others she holds it, but does not open it. She knows what she feels without needing words.',
    symbolism: 'The queen\'s cup is ornate and sealed — alone among the suit, she does not drink from hers. She knows what is inside without needing to look. The ocean extends to the horizon: she is made of the same depth she governs.',
  },
  {
    id: 'king-of-cups',
    name: 'King of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 14,
    symbol: '💧',
    keywords: ['emotionally balanced', 'compassionate', 'diplomatic'],
    upright: 'Emotionally balanced, compassionate, diplomatic, wisdom, control.',
    reversed: 'Self-compassion, inner feelings, moodiness, emotionally manipulative.',
    description: 'A king sits on a stone throne above a turbulent sea, utterly calm. Around him the waves crash — but he remains the master of his emotions.',
    symbolism: 'The king\'s throne floats on a churning sea — yet he is perfectly still. A fish leaps to his right; a ship sails behind. The water is wild; he is not. Mastery of emotion does not mean its absence — it means its perfect governance.',
  },

  // ── Swords ────────────────────────────────────────────────────────────────
  {
    id: 'ace-of-swords',
    name: 'Ace of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 1,
    symbol: '⚔️',
    keywords: ['breakthroughs', 'new ideas', 'mental clarity', 'success'],
    upright: 'Breakthroughs, new ideas, mental clarity, success, truth, justice.',
    reversed: 'Inner clarity, re-thinking an idea, cloudy thinking, confusion.',
    description: 'A hand emerges from a cloud brandishing a great sword. A crown with laurels hangs from the tip — clarity of mind is a crown unto itself.',
    symbolism: 'A hand emerges from cloud brandishing a crowned sword — clarity of mind is the highest victory, its laurel already waiting. The olive branch and the sword tip together signal that truth, though sharp, brings peace.',
  },
  {
    id: 'two-of-swords',
    name: 'Two of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 2,
    symbol: '⚔️',
    keywords: ['difficult decisions', 'weighing options', 'stalemate', 'denial'],
    upright: 'Difficult decisions, weighing options, an impasse, stalemate.',
    reversed: 'Indecision, confusion, information overload, no right choice.',
    description: 'A blindfolded woman holds two swords crossed before her. Behind her, a crescent moon reflects on water. She refuses to see — or cannot.',
    symbolism: 'Two swords cross before the blindfolded woman\'s heart — the decision is guarded from feeling as much as from sight. Crescent moon on the water behind: the truth is already reflected in the depths. The blindfold is the last barrier.',
  },
  {
    id: 'three-of-swords',
    name: 'Three of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 3,
    symbol: '⚔️',
    keywords: ['heartbreak', 'suffering', 'grief', 'rejection', 'separation'],
    upright: 'Heartbreak, suffering, grief, rejection, separation, sorrow.',
    reversed: 'Optimism, forgiveness, recovery, moving on, releasing pain.',
    description: 'Three swords pierce a red heart against a stormy sky. It is stark, painful, and honest — grief does not mince words.',
    symbolism: 'Three swords pierce a heart directly — there is no symbol of softening or hope in this image. The stormy sky is honest. The card does not pretend that grief is anything other than what it is: real, sharp, and necessary.',
  },
  {
    id: 'four-of-swords',
    name: 'Four of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 4,
    symbol: '⚔️',
    keywords: ['rest', 'relaxation', 'peaceful contemplation', 'recuperation'],
    upright: 'Rest, relaxation, peaceful contemplation, recuperation, meditative retreat.',
    reversed: 'Exhaustion, burnout, deep contemplation, stagnation, restlessness.',
    description: 'A knight lies in effigy on a tomb, hands in prayer, while three swords hang above and one lies below. Rest is not weakness — it is strategy.',
    symbolism: 'A knight rests in effigy while three swords hang above and one is sheathed below. Through stained glass behind him, a scene of healing and benediction. Rest is not defeat — it is the strategic pause before the next decisive movement.',
  },
  {
    id: 'five-of-swords',
    name: 'Five of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 5,
    symbol: '⚔️',
    keywords: ['unbridled ambition', 'win at all costs', 'sneakiness', 'conflict'],
    upright: 'Conflict, disagreements, competition, defeat, winning at all costs.',
    reversed: 'Reconciliation, making amends, past resentment, change, moving forward.',
    description: 'A smirking figure collects swords while defeated opponents walk away. The victory is hollow — something was lost in how this was won.',
    symbolism: 'The victor\'s smirk as he gathers swords and the defeated walk away. The troubled, tearing sky witnesses something unclean. The victory is technically complete — yet two swords remain on the ground. Something in the win is already unraveling.',
  },
  {
    id: 'six-of-swords',
    name: 'Six of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 6,
    symbol: '⚔️',
    keywords: ['transition', 'change', 'rite of passage', 'releasing baggage'],
    upright: 'Transition, change, rite of passage, releasing baggage, moving on.',
    reversed: 'Personal transition, resistance to change, unfinished business.',
    description: 'A ferryman guides passengers across still water. Six swords stand in the bow of the boat — the travelers carry their wounds, but move forward.',
    symbolism: 'Six swords stand upright in the prow — the wounds are brought along but are no longer wielded. Water rougher on one side, calmer on the other: the leaving is already working. The ferryman guides; the passengers need only stay in the boat.',
  },
  {
    id: 'seven-of-swords',
    name: 'Seven of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 7,
    symbol: '⚔️',
    keywords: ['betrayal', 'deception', 'getting away with something', 'stealth'],
    upright: 'Betrayal, deception, getting away with something, acting strategically.',
    reversed: 'Imposter syndrome, self-deceit, coming clean, turning over a new leaf.',
    description: 'A figure sneaks away from a camp with five swords while two remain. He looks back — perhaps to see if he is seen, perhaps with regret.',
    symbolism: 'Five swords are taken; two left behind — the act is incomplete, and something in the backward glance acknowledges it. The camp is still visible. The tents suggest community abandoned. Clever strategy and self-deception wear the same face here.',
  },
  {
    id: 'eight-of-swords',
    name: 'Eight of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 8,
    symbol: '⚔️',
    keywords: ['imprisonment', 'entrapment', 'self-victimization', 'negative thinking'],
    upright: 'Imprisonment, entrapment, self-victimization, negative thinking.',
    reversed: 'Self-limiting beliefs, inner critic, releasing negative thoughts, freedom.',
    description: 'A blindfolded and bound woman stands among eight swords. The path is clear — the bonds are loose — but she cannot see her own way out.',
    symbolism: 'Eight swords are planted in the earth around a bound and blindfolded woman — but the bonds are loose and the swords do not touch her. The path is open. The castle is visible in the distance. The prison is entirely constructed from within.',
  },
  {
    id: 'nine-of-swords',
    name: 'Nine of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 9,
    symbol: '⚔️',
    keywords: ['anxiety', 'worry', 'fear', 'depression', 'nightmares'],
    upright: 'Anxiety, worry, fear, depression, nightmares, inner turmoil.',
    reversed: 'Inner turmoil, deep-seated fears, secrets, releasing worry, recovery.',
    description: 'A figure sits upright in bed, head in hands, beneath nine swords on a wall. The night is dark. The fears are real — but morning does come.',
    symbolism: 'Nine swords hang on the wall above a figure who sits with their head in their hands at the darkest hour. The quilt below shows roses and astrological symbols — beauty and anxiety share the same space. The fears are real. And morning still comes.',
  },
  {
    id: 'ten-of-swords',
    name: 'Ten of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 10,
    symbol: '⚔️',
    keywords: ['painful endings', 'deep wounds', 'betrayal', 'loss', 'rock bottom'],
    upright: 'Painful endings, deep wounds, betrayal, loss, rock bottom, collapse.',
    reversed: 'Recovery, regeneration, resisting an inevitable end, only upward now.',
    description: 'A figure lies face down with ten swords in their back. Above, the sky begins to lighten over dark water. Even the worst ending holds a dawn.',
    symbolism: 'Ten swords pierce a figure face-down on the ground. Yet the sky above the dark water is brightening — a thin line of golden dawn at the horizon. The darkness is complete. So is the certainty that from this point, only one direction remains.',
  },
  {
    id: 'page-of-swords',
    name: 'Page of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 11,
    symbol: '⚔️',
    keywords: ['new ideas', 'curiosity', 'thirst for knowledge', 'new ways'],
    upright: 'New ideas, curiosity, thirst for knowledge, new ways of communicating.',
    reversed: 'Self-expression, all talk no action, haste, deception.',
    description: 'A young figure stands on a windy hilltop, sword raised and alert. Every movement is watched — the page sees everything and misses nothing.',
    symbolism: 'A vigilant page stands on a windswept hilltop, sword raised and eyes alert. The turbulent clouds and bending trees match the page\'s restless, probing mind. Everything moves; the page alone stands still enough to observe it all.',
  },
  {
    id: 'knight-of-swords',
    name: 'Knight of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 12,
    symbol: '⚔️',
    keywords: ['ambition', 'action', 'drive', 'fast-thinking'],
    upright: 'Ambition, action, drive, fast-thinking, fearless, assertive.',
    reversed: 'Restless, unfocused, impulsive, burn out, scattered energy.',
    description: 'A knight charges into battle on a galloping horse, sword raised. He does not hesitate — he does not slow down — he cannot be stopped.',
    symbolism: 'The knight charges at full gallop, sword raised, trees bending violently in the wind of his passing. Birds scatter from his path. He does not look left or right. Whether what lies ahead deserves such force has not yet been asked.',
  },
  {
    id: 'queen-of-swords',
    name: 'Queen of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 13,
    symbol: '⚔️',
    keywords: ['independent', 'unbiased judgement', 'clear boundaries', 'direct'],
    upright: 'Independent, unbiased judgement, clear boundaries, direct communication.',
    reversed: 'Overly-emotional, easily influenced, bitchy, cold-hearted.',
    description: 'A crowned queen sits alone on a high throne, sword raised, one hand extended as if beckoning truth. She has learned to love clarity over comfort.',
    symbolism: 'The queen sits alone at great height, sword raised, one hand extended — summoning truth rather than defending against it. Butterflies on her crown are transformation through thought. She has paid the price of clarity and wears it without apology.',
  },
  {
    id: 'king-of-swords',
    name: 'King of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 14,
    symbol: '⚔️',
    keywords: ['mental clarity', 'intellectual power', 'authority', 'truth'],
    upright: 'Mental clarity, intellectual power, authority, truth, clear thinking.',
    reversed: 'Quiet power, inner truth, misuse of power, manipulation.',
    description: 'A stern king sits on a throne of stone butterflies, sword raised vertically. He is the embodiment of pure intellect and unbending principle.',
    symbolism: 'Butterflies and sylphs carved into the king\'s stone throne — transformation through thought, the airy realm he rules. His sword points straight upward: absolute principle, vertical, uncompromising, identical from every angle.',
  },

  // ── Pentacles ─────────────────────────────────────────────────────────────
  {
    id: 'ace-of-pentacles',
    name: 'Ace of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 1,
    symbol: '🌿',
    keywords: ['opportunity', 'prosperity', 'new venture', 'manifestation'],
    upright: 'A new financial or career opportunity, manifestation, abundance, security.',
    reversed: 'Lost opportunity, lack of planning and foresight, lost focus on material world.',
    description: 'A divine hand offers a single golden pentacle through a wreath of flowers. A garden path winds toward distant mountains — an invitation to abundance.',
    symbolism: 'A single golden pentacle is offered through a floral archway — one solid, tangible opportunity extended with divine patience. The garden path winds toward distant mountains: the work is long and the terrain is real, but the first step is a gift.',
  },
  {
    id: 'two-of-pentacles',
    name: 'Two of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 2,
    symbol: '🌿',
    keywords: ['multiple priorities', 'time management', 'balance', 'adaptability'],
    upright: 'Multiple priorities, time management, balance, adaptability, flexibility.',
    reversed: 'Over-committed, disorganized, reprioritization needed, unbalanced.',
    description: 'A jester juggles two pentacles connected by an infinity loop. Behind him, ships rock on rough seas — yet he balances effortlessly.',
    symbolism: 'The infinity loop linking two pentacles: this balance is not a fixed state but a dynamic, continuous practice. Ships toss in rough water behind the jester who smiles — he knows that equilibrium is always earned, never settled.',
  },
  {
    id: 'three-of-pentacles',
    name: 'Three of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 3,
    symbol: '🌿',
    keywords: ['teamwork', 'collaboration', 'building', 'learning', 'implementation'],
    upright: 'Teamwork, collaboration, building, learning, implementation, mastery.',
    reversed: 'Lack of teamwork, disorganized, group conflict, poor collaboration.',
    description: 'A craftsman works on a cathedral while an architect and monk consult plans. Three skills, one vision — the work grows through shared effort.',
    symbolism: 'Craftsman, architect, and monk meet before the cathedral arch — three different kinds of knowing in service of one structure. Three pentacles are carved above them. Mastery here is not solitary. It lives in the space between three open minds.',
  },
  {
    id: 'four-of-pentacles',
    name: 'Four of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 4,
    symbol: '🌿',
    keywords: ['saving money', 'security', 'conservatism', 'scarcity'],
    upright: 'Saving money, security, conservatism, scarcity, control, stability.',
    reversed: 'Over-spending, greed, self-protection, hoarding, instability.',
    description: 'A seated figure clutches a pentacle to his chest, one beneath each foot, one on his crown. He holds on tightly — but at what cost?',
    symbolism: 'A figure clutches one pentacle to his chest, balances one on his crown, and stands on two more. His city — the life he guards — is behind him, unreached. Security purchased by standing still is a life not yet lived.',
  },
  {
    id: 'five-of-pentacles',
    name: 'Five of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 5,
    symbol: '🌿',
    keywords: ['financial loss', 'poverty', 'lack mindset', 'isolation'],
    upright: 'Financial loss, poverty, lack mindset, isolation, worry, hardship.',
    reversed: 'Recovery from financial loss, spiritual poverty, overcoming hardship.',
    description: 'Two ragged figures trudge through snow past a glowing church window. They are cold and in need — yet do not think to knock and ask.',
    symbolism: 'Two figures walk through snow past a lit church window. Warmth glows just behind the glass — but they do not stop to knock. Scarcity teaches us to keep moving past what could receive us. The door may not even be locked.',
  },
  {
    id: 'six-of-pentacles',
    name: 'Six of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 6,
    symbol: '🌿',
    keywords: ['giving', 'receiving', 'sharing wealth', 'generosity'],
    upright: 'Giving, receiving, sharing wealth, generosity, charity, gratitude.',
    reversed: 'Self-care, unpaid debts, one-sided charity, power dynamics.',
    description: 'A merchant weighs coins on scales while giving to beggars. Who holds the scales? Who decides how much is enough?',
    symbolism: 'The merchant holds scales while giving to two kneeling figures. The scales do not just measure coins — they measure the power to decide who receives what. The act of giving is generous. The architecture of giving can still be unequal.',
  },
  {
    id: 'seven-of-pentacles',
    name: 'Seven of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 7,
    symbol: '🌿',
    keywords: ['long-term view', 'sustainable results', 'perseverance', 'investment'],
    upright: 'Long-term view, sustainable results, perseverance, investment, milestone.',
    reversed: 'Lack of long-term vision, limited success or reward, procrastination.',
    description: 'A farmer leans on his hoe, surveying the pentacles growing on his vine. The harvest is close — but patience is still required.',
    symbolism: 'A farmer leans on his hoe, surveying seven pentacles on a vine he has tended. The harvest is close — but it is not yet here. He has learned the discipline of waiting well: invested, patient, and still present to what is growing.',
  },
  {
    id: 'eight-of-pentacles',
    name: 'Eight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 8,
    symbol: '🌿',
    keywords: ['apprenticeship', 'repetitive tasks', 'mastery', 'skill development'],
    upright: 'Apprenticeship, repetitive tasks, mastery, skill development, quality.',
    reversed: 'Self-development, perfectionism, misdirected activity, no motivation.',
    description: 'A craftsman sits alone, carving star after star into pentacles. His focus is absolute — he has devoted himself to his craft completely.',
    symbolism: 'A craftsman sits alone, carving star after star. Six are complete and hung; a seventh nears completion; an eighth begins. Mastery does not live in the finished product alone — it lives in the willingness to do the work one more time.',
  },
  {
    id: 'nine-of-pentacles',
    name: 'Nine of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 9,
    symbol: '🌿',
    keywords: ['abundance', 'luxury', 'self-sufficiency', 'financial independence'],
    upright: 'Abundance, luxury, self-sufficiency, financial independence, enjoyment.',
    reversed: 'Self-worth, over-investment in work, hustling, financial setbacks.',
    description: 'An elegantly dressed woman stands in a lush vineyard, a hooded falcon on her wrist. She has built this — and she enjoys it fully.',
    symbolism: 'A woman in an elegant robe stands in her vineyard, a trained falcon on her gloved wrist. Snails move at her feet — she has learned that slowness is its own richness. She built all of this. She enjoys it without apology.',
  },
  {
    id: 'ten-of-pentacles',
    name: 'Ten of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 10,
    symbol: '🌿',
    keywords: ['wealth', 'financial security', 'family', 'long-term success'],
    upright: 'Wealth, financial security, family, long-term success, legacy, stability.',
    reversed: 'The dark side of wealth, financial failure or loss, loneliness.',
    description: 'An old man sits amid dogs and family as ten pentacles form the Tree of Life around the scene. This is inherited wealth, enduring legacy.',
    symbolism: 'Ten pentacles form the Tree of Life around an elder, his family, and his dogs. The pattern is not decoration — it is the architecture of what has been built and what endures. Legacy is the name for love that outlasts the one who gave it.',
  },
  {
    id: 'page-of-pentacles',
    name: 'Page of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 11,
    symbol: '🌿',
    keywords: ['manifestation', 'financial opportunity', 'skill development'],
    upright: 'Manifestation, financial opportunity, skill development, learning.',
    reversed: 'Lack of progress, procrastination, learn from failure, bad news.',
    description: 'A young figure stands in a flowered field gazing at a golden pentacle held before them. They see in it a future — and they are ready to work.',
    symbolism: 'The page holds a golden pentacle aloft in a field of flowers, studying it as if it were a lens through which the future can be seen and worked toward. The mountains in the distance are not obstacles — they are destinations.',
  },
  {
    id: 'knight-of-pentacles',
    name: 'Knight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 12,
    symbol: '🌿',
    keywords: ['hard work', 'productivity', 'routine', 'conservatism'],
    upright: 'Hard work, productivity, routine, conservatism, methodical, responsible.',
    reversed: 'Self-discipline, boredom, feeling stuck, perfectionism, laziness.',
    description: 'A knight sits motionless on a heavy horse, studying a single pentacle. He does not move until he is sure — reliable, patient, enduring.',
    symbolism: 'A heavy horse stands still as its rider studies a single pentacle with complete attention. Unlike every other knight — there is no motion. No gallop, no quest. He moves only when he is certain. This is the discipline that builds what endures.',
  },
  {
    id: 'queen-of-pentacles',
    name: 'Queen of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 13,
    symbol: '🌿',
    keywords: ['nurturing', 'practical', 'providing financially', 'a working parent'],
    upright: 'Nurturing, practical, providing financially, a working parent, down-to-earth.',
    reversed: 'Financial independence, self-care, work-home conflict, smothering.',
    description: 'A queen sits on a flower-carved throne in a garden, a hare leaping nearby. She holds her pentacle tenderly — wealth is something she tends.',
    symbolism: 'A queen on a throne carved with fruits and flowers holds her pentacle with genuine tenderness — not clutching, but cradling. A hare leaps nearby: fertility and abundance as living companions, not trophies. She grows what she loves.',
  },
  {
    id: 'king-of-pentacles',
    name: 'King of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 14,
    symbol: '🌿',
    keywords: ['wealth', 'business', 'leadership', 'security', 'discipline'],
    upright: 'Wealth, business, leadership, security, discipline, abundance, provider.',
    reversed: 'Financially inept, obsessed with wealth and status, stubborn.',
    description: 'A king enthroned amid vines and bull-carved stone holds his pentacle with casual mastery. Everything he has built surrounds and supports him.',
    symbolism: 'Bull-carved stone and living vines surround the king who holds his pentacle with relaxed certainty. His robe is covered with grape clusters — abundance is woven into how he moves. He built all of this. It supports him now the way roots support a tree.',
  },
]

export default tarotCards

export function getCardBySlug(slug: string): TarotCard | undefined {
  return tarotCards.find((c) => c.id === slug)
}

export function getDailyCard(): TarotCard {
  const today = new Date()
  const seed = today.getFullYear() * 10000 + (today.getMonth() + 1) * 100 + today.getDate()
  return tarotCards[seed % tarotCards.length]
}

const GITHUB_IMAGES = 'https://raw.githubusercontent.com/krates98/tarotcardapi/main/images'

// Cards whose filenames deviate from the standard lowercase-no-spaces pattern
const IMAGE_OVERRIDES: Record<string, string> = {
  'The Lovers': 'TheLovers.jpg',   // mixed-case + .jpg in the repo
  'Strength':   'thestrength.jpeg', // repo adds "the" prefix even though card name doesn't
}

export function getCardImagePath(card: TarotCard): string {
  if (IMAGE_OVERRIDES[card.name]) {
    return `${GITHUB_IMAGES}/${IMAGE_OVERRIDES[card.name]}`
  }
  const filename = card.name.toLowerCase().replace(/\s+/g, '')
  return `${GITHUB_IMAGES}/${filename}.jpeg`
}
